/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterAvatar: typeof import('./src/components/character_cards/CharacterAvatar.vue')['default']
    ChatScreen: typeof import('./src/components/chat_screen/ChatScreen.vue')['default']
    DeleteConfirm: typeof import('./src/components/DeleteConfirm.vue')['default']
    EditMessageModal: typeof import('./src/components/chat_screen/EditMessageModal.vue')['default']
    ExtractorCharacterModal: typeof import('./src/components/chat_screen/ExtractorCharacterModal.vue')['default']
    GlobalWorldbookManager: typeof import('./src/components/worldbook/GlobalWorldbookManager.vue')['default']
    Index: typeof import('./src/components/character_cards/Index.vue')['default']
    LLMIndex: typeof import('./src/components/llm_models/LLMIndex.vue')['default']
    LLMOptionsModal: typeof import('./src/components/llm_models/LLMOptionsModal.vue')['default']
    LLMProviderSelect: typeof import('./src/components/common/LLMProviderSelect.vue')['default']
    LoadingScreen: typeof import('./src/components/common/LoadingScreen.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MessageButtons: typeof import('./src/components/chat_screen/MessageButtons.vue')['default']
    Modal: typeof import('./src/components/llm_models/Modal.vue')['default']
    ModalImport: typeof import('./src/components/character_cards/ModalImport.vue')['default']
    NavConfig: typeof import('./src/components/NavConfig.vue')['default']
    PresetConfig: typeof import('./src/components/PresetConfig.vue')['default']
    ProfileList: typeof import('./src/components/profile/ProfileList.vue')['default']
    ProfileModal: typeof import('./src/components/profiles/ProfileModal.vue')['default']
    ProfileSelectorModal: typeof import('./src/components/profiles/ProfileSelectorModal.vue')['default']
    SaveButton: typeof import('./src/components/common/SaveButton.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Translate: typeof import('./src/components/character_cards/Translate.vue')['default']
    WorldbookEditor: typeof import('./src/components/worldbook/WorldbookEditor.vue')['default']
    WorldbookEntryForm: typeof import('./src/components/worldbook/WorldbookEntryForm.vue')['default']
    WorldbookLinker: typeof import('./src/components/worldbook/WorldbookLinker.vue')['default']
    WorldbookTable: typeof import('./src/components/worldbook/WorldbookTable.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
